import Foundation
import CoreGraphics
import PixelKit

/// 菜单栏图标（18×18 美术像素，按 2 倍最近邻放大成 36×36 再当 18 pt 的图用，所以 Retina 下每个美术像素正好 2 个设备像素）。
/// normal / busy 是模板图（只用黑色 + 透明，系统会按菜单栏明暗自动着色）；waiting 是彩色的举手图标（不做成模板）。
public enum MenuBarIcon {
    public enum Kind: String, CaseIterable { case normal, busy, waiting }

    static let normalRows = """
    ..................
    ..##############..
    ..#............#..
    ..#............#..
    ..#............#..
    ..#............#..
    ..#............#..
    ..#............#..
    ..##############..
    ......######......
    ....##########....
    ......######......
    ......######......
    ......######......
    .....########.....
    ....##########....
    ...############...
    ..................
    """
    static let busyRows = """
    ..................
    ..##############..
    ..#.##########.#..
    ..#............#..
    ..#.#######....#..
    ..#............#..
    ..#.#####......#..
    ..#............#..
    ..##############..
    ......######......
    ....##########....
    ......######......
    ......######......
    ......######......
    .....########.....
    ....##########....
    ...############...
    ..................
    """
    // 彩色：橙色衣服、肤色头、右手举起，屏幕上一个黄色「!」
    static let waitingRows = """
    ..................
    ..##############..
    ..#yyyyyyyyyyyy#..
    ..#yyyyyy..yyyy#..
    ..#yyyyyy..yyyy#..
    ..#yyyyyy..yyyy#..
    ..#yyyyyyyyyyyy#..
    ..#yyyyyy..yyyy#.s
    ..##############.s
    ......######....ss
    ....##########.ss.
    ......ssssss..ss..
    ......ssssss..s...
    ......ssssss......
    .....oooooooo.....
    ....oooooooooo....
    ...oooooooooooo...
    ..................
    """

    static func rows(_ k: Kind) -> String {
        switch k { case .normal: return normalRows; case .busy: return busyRows; case .waiting: return waitingRows }
    }

    /// 36×36 像素的 CGImage（调用方按 18×18 pt 使用）。
    public static func image(_ k: Kind) -> CGImage? {
        let lines = rows(k).split(separator: "\n").map(String.init)
        let c = Canvas(width: 18, height: 18)
        let colors: [Character: RGBA8] = [
            "#": k == .waiting ? RGBA8(hex: 0x2A2230) : RGBA8(0, 0, 0, 255),
            "y": RGBA8(hex: 0xFFD54A), "s": RGBA8(hex: 0xF0BC9E), "o": RGBA8(hex: 0xF2854A), "w": RGBA8(hex: 0xFFFFFF),
        ]
        for (y, l) in lines.enumerated() { for (x, ch) in l.enumerated() { if let col = colors[ch] { c.setRaw(x, y, color: col) } } }
        return FrameRenderer.render(Frame(canvas: c), zoom: 2, scale: 1)
    }
}
