import Foundation
import PixelKit

extension CharacterArt {
    // MARK: 配饰
    //
    // acc.<配饰>.<朝向>：
    //  · headphones / beanie / hairpin（5 个朝向）、glasses（front / q34front / side）：头上的配饰，和头发共用 16×20 的画布，
    //    头盒子左上角在 hairPad = (2,3)，锚点 head = hairPad；渲染时和头发一样贴（画在头发之后）。
    //  · scarf（5 个朝向）：躯干上的叠层，14×10，第 0 行 = 肩线上沿，锚点 neck = (7,0)（3/4 是 (8,0)），和 torso.tee.* 一致；
    //    画在躯干和头之后，位置和躯干一样（让 scarf 的 neck 锚点落在躯干的 neck 锚点上）。
    // 下面的 ASCII 直接按「画布坐标」写（16 列，第 0 列 = 画布最左；头盒子第 x 列 = 画布第 x+2 列），rows 的第一行对应画布第 y0 行。
    // 字符：a 点缀  A 点缀影（最深的点缀色）  u 点缀高光  n 白点  l 镜片  t 衣服阴影（围巾投在衣服上的影子）。
    // 全部只用点缀色三级（u/a/A）+ n、l，没有写死颜色。

    /// 逐行检查过宽度的 16 列 ASCII → 16×20 格子（第一行对应画布第 y0 行）。
    private static func accRows(_ rows: String, y0: Int, _ what: String) -> Grid {
        var ls = rows.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        while let f = ls.first, f.trimmingCharacters(in: .whitespaces).isEmpty { ls.removeFirst() }
        while let l = ls.last, l.trimmingCharacters(in: .whitespaces).isEmpty { ls.removeLast() }
        var g = Grid(w: hairW, h: hairH)
        for (i, l) in ls.enumerated() {
            let t = l.trimmingCharacters(in: .whitespaces)
            precondition(t.count == hairW, "\(what) 第 \(y0 + i) 行宽度是 \(t.count)，应为 \(hairW)：\(t)")
            precondition(y0 + i < hairH, "\(what) 行数超出")
            for (x, c) in t.enumerated() where c != "." {
                guard let r = Role.chars[c] else { preconditionFailure("\(what) 里有不认识的字符「\(c)」") }
                g[x, y0 + i] = r
            }
        }
        return g
    }

    private static func addAcc(_ book: SpriteBook, _ name: String, _ facing: Facing, y0: Int, _ rows: String) {
        let what = "acc.\(name).\(facing.name)"
        book.add(accRows(rows, y0: y0, what).sprite(name: what, anchors: ["head": hairPad]))
    }

    static func buildAccessories(_ book: SpriteBook) {
        buildHeadphones(book)
        buildBeanies(book)
        buildHairpins(book)
        buildGlasses(book)
        buildScarves(book)
    }

    // 点缀色的三级材质：高光 u / 基色 a / 阴影 A（选择性描边：左上边用基色，右下边用 A）。
    private static let accentMat = Material(hi: Role.accent2, base: Role.accent, sh: Role.accent, out: Role.accentSh)

    /// 16 列 '#' 蒙版（第一行对应画布第 y0 行）→ 16×20 位图。
    private static func accBits(_ rows: String, y0: Int, _ what: String) -> Bitmap {
        let m = Bitmap(rows)
        precondition(m.w == hairW, "\(what) 蒙版宽度是 \(m.w)，应为 \(hairW)")
        var b = Bitmap(w: hairW, h: hairH)
        for y in 0..<m.h { for x in 0..<m.w where m[x, y] { b[x, y0 + y] = true } }
        return b
    }

    // ============ 耳机 ============
    // 头带贴着头发轮廓拱过头顶（外圈 1 格在头发外面，里圈 1 格盖在头发上），两侧一对深色耳罩盖住耳朵。
    // 背面/3/4 背面的近侧耳罩宽 4–5；正面的耳罩只盖头发（脸的左右边缘留给脸）；侧面是一个 5×5 的圆耳罩 + 一条微微前倾的头带。
    static func buildHeadphones(_ book: SpriteBook) {
        //      0123456789012345
        addAcc(book, "headphones", .back, y0: 2, """
        .....aaaaaA.....
        ....auuuaaaA....
        ...au......aA...
        ..au........aA..
        .au..........aA.
        .au..........aA.
        .AA..........AA.
        .aaa........aaA.
        aaAAA......aaAAA
        auAAA......uaAAA
        aaAAA......aaAAA
        .AAA........AAA.
        """)
        addAcc(book, "headphones", .threeQuarterBack, y0: 2, """
        .....aaaaaA.....
        ....auuuaaaA....
        ...au......aA...
        ..au........aA..
        .au..........aA.
        .au..........aA.
        .AA..........AA.
        .aa..........aaa
        aaA........aaAAA
        aAA........uaAAA
        aaA........aaAAA
        .AA..........AAA
        """)
        addAcc(book, "headphones", .side, y0: 2, """
        .......ua.......
        .......ua.......
        ......ua........
        ......ua........
        ......ua........
        .....ua.........
        .....ua.........
        .....AA.........
        ....aaaA........
        ...aauaaA.......
        ...aaaaaA.......
        ...aaaaAA.......
        ....AAAA........
        """)
        addAcc(book, "headphones", .threeQuarterFront, y0: 2, """
        .....aaaaaA.....
        ....auuuaaaA....
        ...au......aA...
        ..au........aA..
        .au..........aA.
        .au..........aA.
        .AA..........AA.
        .aaa............
        aaAAA........aA.
        auAAA........aA.
        aaAAA........aA.
        .AAA............
        """)
        // 正面：脸的左右边缘（画布第 4 列 / 第 11 列）不能被耳罩盖住，所以耳罩比背面窄一格（4 宽，只盖头发）
        addAcc(book, "headphones", .front, y0: 2, """
        .....aaaaaA.....
        ....auuuaaaA....
        ...au......aA...
        ..au........aA..
        .au..........aA.
        .au..........aA.
        .AA..........AA.
        .aaa........aaA.
        aaAA........aAAA
        auAA........uAAA
        aaAA........aAAA
        .AAA........AAA.
        """)
    }
}

extension CharacterArt {
    // ============ 毛线帽 ============
    // 轮廓（蒙版）比头发大一圈；每一列最下面 cuffRows 格是翻边（竖罗纹），上面是帽身（淡淡的竖纹）。
    // 帽顶有一个白色的小绒球（rows 0–4，下面两行盖在帽顶上）。
    static func buildBeanies(_ book: SpriteBook) {
        func beanie(_ facing: Facing, ribCenter: Double = 7.5, sil: String, cuffRows: Int = 3) {
            let what = "acc.beanie.\(facing.name)"
            let all = accBits(sil, y0: 4, what)
            var dome = Bitmap(w: hairW, h: hairH), cuff = Bitmap(w: hairW, h: hairH)
            var bottoms = [Int](repeating: -1, count: hairW)
            for x in 0..<hairW { for y in 0..<hairH where all[x, y] { bottoms[x] = y } }
            for x in 0..<hairW where bottoms[x] >= 0 {
                for y in 0..<hairH where all[x, y] {
                    if y > bottoms[x] - cuffRows { cuff[x, y] = true } else { dome[x, y] = true }
                }
            }
            var g = ShadeKit.shade(dome, accentMat)
            // 帽身的竖罗纹：几条隔行的阴影短线
            let shift = Int((ribCenter - 7.5).rounded(.up))
            for y in 5..<hairH { for x in [4, 6, 9, 11].map({ $0 + shift }) where x >= 0 && x < hairW && dome[x, y] && g[x, y] == Role.accent { g[x, y] = Role.accentSh } }
            var c = Grid(w: hairW, h: hairH)
            for x in 0..<hairW where bottoms[x] >= 0 {
                for y in 0..<hairH where cuff[x, y] {
                    let top = y == bottoms[x] - cuffRows + 1, bot = y == bottoms[x]
                    if bot { c[x, y] = Role.accentSh }
                    else if top { c[x, y] = x % 2 == 0 ? Role.accent2 : Role.accent }
                    else { c[x, y] = x % 2 == 0 ? Role.accent : Role.accentSh }
                }
            }
            g.overlay(c)
            // 绒球：6×5，白色（n）的毛球，坐在帽顶正中（下面两行盖在帽顶上）；左上边缘用点缀高光，右下用点缀色，几点毛茸茸的杂色
            g.overlay(accRows("""
            ......uuua......
            .....unnnna.....
            .....unnnuA.....
            .....unnuuA.....
            ......AAAA......
            """, y0: 0, what))
            book.add(g.sprite(name: what, anchors: ["head": hairPad]))
        }
        beanie(.back, sil: """
        ...##########...
        ..############..
        .##############.
        .##############.
        .##############.
        .##############.
        .##############.
        ...##########...
        """)
        beanie(.threeQuarterBack, ribCenter: 8, sil: """
        ...##########...
        ..############..
        .##############.
        .##############.
        .##############.
        .##############.
        .###########....
        ...########.....
        """)
        beanie(.side, ribCenter: 8.5, sil: """
        ...##########...
        ..############..
        .##############.
        .##############.
        .##########.....
        .#######........
        .####...........
        .##.............
        """)
        beanie(.threeQuarterFront, ribCenter: 8, sil: """
        ...##########...
        ..############..
        .##############.
        .##############.
        .############...
        .#######........
        .###............
        """)
        beanie(.front, sil: """
        ...##########...
        ..############..
        .##############.
        .##############.
        ..############..
        """, cuffRows: 2)
    }
}

extension CharacterArt {
    // ============ 发夹（蝴蝶结）============
    static func buildHairpins(_ book: SpriteBook) {
        // 蝴蝶结 6×4：外端高、中间窄（像领结），中间一个深色的结；左上一点高光，右下阴影。
        // 夹在 buddy 的「右手边」：背面/3/4 背面在画面右侧（后脑右侧），侧面在耳朵上方，3/4 正面/正面在画面左侧的刘海上——
        // 这样从背面转到正面时，蝴蝶结跟着头一起转过去，不会跳到另一边。
        //      0123456789012345
        for f in [Facing.back, .threeQuarterBack] {
            addAcc(book, "hairpin", f, y0: 6, """
            .......na...a...
            .......aaAAaa...
            .......aaAAaA...
            .......aA...A...
            """)
        }
        addAcc(book, "hairpin", .side, y0: 5, """
        .....na...a.....
        .....aaAAaa.....
        .....aaAAaA.....
        .....aA...A.....
        """)
        for f in [Facing.threeQuarterFront, .front] {
            addAcc(book, "hairpin", f, y0: 5, """
            ...na...a.......
            ...aaAAaa.......
            ...aaAAaA.......
            ...aA...A.......
            """)
        }
    }

    // ============ 眼镜（front / q34front / side）============
    static func buildGlasses(_ book: SpriteBook) {
        addAcc(book, "glasses", .front, y0: 9, """
        .....nA..nA.....
        ....A..AA..A....
        ....A......A....
        ....A.l...lA....
        .....AA..AA.....
        """)
        addAcc(book, "glasses", .threeQuarterFront, y0: 9, """
        ......nA..A.....
        ...AAA..AA.A....
        .....A.....A....
        .....A.l..lA....
        ......AA..A.....
        """)
        addAcc(book, "glasses", .side, y0: 9, """
        ..........nA....
        .....AAAAA..A...
        .........A..A...
        .........A.lA...
        ..........AA....
        """)
    }

    // ============ 围巾（躯干上的叠层，14×10）============
    // 第 0 行 = 肩线上沿，和 torso.tee.* 一样：锚点 neck 背面/侧面/正面 (7,0)，3/4 是 (8,0)。
    // 绕脖子一圈（斜条纹）+ 尾巴（横条纹，盖在圈上垂下来，末端流苏）+ 正面的结。
    static func buildScarves(_ book: SpriteBook) {
        func mask14(_ rows: String, _ what: String) -> Bitmap {
            let m = Bitmap(rows)
            precondition(m.w == 14, "\(what) 蒙版宽度是 \(m.w)，应为 14")
            var b = Bitmap(w: 14, h: 10)
            for y in 0..<min(m.h, 10) { for x in 0..<14 where m[x, y] { b[x, y] = true } }
            return b
        }
        /// wrap：绕脖子的圈；tails：每条尾巴一张蒙版（后面的盖在前面的上面）；knot：结。
        /// ring(x, y) 为真的格子是圈上的淡色条，tail(y) 为真的行是尾巴上的淡色条。
        func scarf(_ facing: Facing, neckX: Int, wrap: String, tails: [String], knot: String? = nil,
                   ring: @escaping (Int, Int) -> Bool = { x, y in (x + y) % 3 == 0 }, tail: @escaping (Int) -> Bool = { $0 % 3 == 1 }) {
            let what = "acc.scarf.\(facing.name)"
            var g = Grid(w: 14, h: 10)
            let wm = mask14(wrap, what)
            var wg = ShadeKit.shade(wm, accentMat, hiBand: false)
            for y in 0..<10 { for x in 0..<14 where wm[x, y] && ring(x, y) && wg[x, y] != Role.accentSh { wg[x, y] = Role.accent2 } }
            g.overlay(wg)
            var tailBits = Bitmap(w: 14, h: 10)
            for t in tails {
                let tm = mask14(t, what)
                tailBits = tailBits.union(tm)
                var tg = ShadeKit.shade(tm, accentMat, hiBand: false)
                for y in 0..<10 { for x in 0..<14 where tm[x, y] && tail(y) && tg[x, y] != Role.accentSh { tg[x, y] = Role.accent2 } }
                // 流苏：尾巴最下面一行的下面，隔一列一根
                for x in 0..<14 {
                    var bot = -1
                    for y in 0..<10 where tm[x, y] { bot = y }
                    guard bot >= 0, bot + 1 < 10 else { continue }
                    if x % 2 == 1 { tg[x, bot + 1] = Role.accentSh; if bot + 2 < 10 { tg[x, bot + 2] = Role.accentSh } }
                    else { tg[x, bot + 1] = Role.accent }
                }
                g.overlay(tg)
            }
            if let k = knot {
                let km = mask14(k, what)
                var kg = ShadeKit.shade(km, accentMat)
                for y in 0..<10 { for x in 0..<14 where km[x, y] && kg[x, y] == Role.accent { kg[x, y] = Role.accent2 } }
                g.overlay(kg)
            }
            // 投在衣服上的影子（用衣服的阴影色 t，所以任何衣服都合适）：圈的下缘一行、尾巴右侧一列（光从左上来）
            var shadow = Grid(w: 14, h: 10)
            for x in 0..<14 {
                var yb = -1
                for y in 0..<10 where wm[x, y] { yb = y }
                if yb >= 0 && yb + 1 < 10 && g[x, yb + 1] == 0 { shadow[x, yb + 1] = Role.clothSh }
            }
            for y in 0..<10 { for x in 0..<13 where tailBits[x, y] && g[x + 1, y] == 0 { shadow[x + 1, y] = Role.clothSh } }
            for y in 0..<10 { for x in 0..<14 where shadow[x, y] != 0 && g[x, y] == 0 { g[x, y] = shadow[x, y] } }
            book.add(g.sprite(name: what, anchors: ["neck": IntPoint(neckX, 0)]))
        }
        scarf(.back, neckX: 7, wrap: """
        ...########...
        .############.
        ..##########..
        """, tails: ["""
        ..............
        ..............
        .......###....
        .......###....
        .......###....
        .......###....
        .......###....
        .......###....
        """])
        scarf(.threeQuarterBack, neckX: 8, wrap: """
        ....########..
        ..###########.
        ...##########.
        """, tails: ["""
        ..............
        ..............
        ........###...
        ........###...
        ........###...
        ........###...
        ........###...
        ........###...
        """])
        scarf(.side, neckX: 7, wrap: """
        ....######....
        ...########...
        ...########...
        """, tails: ["""
        ..............
        ..............
        ...###........
        ...###........
        ...###........
        ...###........
        ...###........
        ...###........
        """, """
        ..............
        ..............
        ........##....
        ........##....
        ........##....
        ........##....
        ..............
        ..............
        """])
        scarf(.threeQuarterFront, neckX: 8, wrap: """
        ...########...
        .############.
        ..##########..
        """, tails: ["""
        ..............
        ..............
        ..............
        .......###....
        .......###....
        .......###....
        .......###....
        .......###....
        """], knot: """
        ..............
        ..............
        ......####....
        ......####....
        """)
        scarf(.front, neckX: 7, wrap: """
        ...########...
        .############.
        ..##########..
        """, tails: ["""
        ..............
        ..............
        ..............
        .......###....
        .......###....
        .......###....
        .......###....
        .......###....
        """], knot: """
        ..............
        ..............
        ......####....
        ......####....
        """)
    }
}
