import Foundation
import PixelKit

extension CharacterArt {
    /// 头盒子 12×13（头 + 头发共 13 高）。头皮/脸是 10×10 的圆脸（第 3–12 行），头发从第 0 行开始盖上去。
    /// 五官只在侧面、3/4 正面、正面上画；背面和 3/4 背面只露出耳朵和一点脸颊。
    /// 所有朝向都是「朝向画面右侧」的版本；朝左直接水平翻转。
    static let skullRows = """
    ............
    ............
    ............
    ...######...
    ..########..
    .##########.
    .##########.
    .##########.
    .##########.
    .##########.
    .##########.
    ..########..
    ...######...
    """

    static func buildHeads(_ book: SpriteBook) {
        let skull = Bitmap(skullRows)
        let anchors: [String: IntPoint] = ["chin": IntPoint(6, 12)]

        // —— 正面 ——
        // 眼睛 2×3（左上角一格高光），两颊各 2 格腮红，嘴是脸下部中间的两格。
        var front = ShadeKit.shade(skull, .skin)
        front.overlay("""
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ...we..we...
        K..ee..ee..K
        ...ee..ee...
        ..bb....bb..
        .....mm.....
        ............
        """)
        book.add(front.sprite(name: "head.front", anchors: anchors.merging(["eyeL": IntPoint(3, 7), "eyeR": IntPoint(7, 7)]) { $1 }))

        // —— 背面 —— 只有两侧的耳朵（头发会盖住大部分）
        var back = ShadeKit.shade(skull, .skin)
        back.overlay("""
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        K..........K
        ............
        ............
        ............
        ............
        """)
        book.add(back.sprite(name: "head.back", anchors: anchors))

        // —— 侧面（朝右）—— 耳朵在中间偏后，眼睛靠前，前端一个小鼻尖
        var side = ShadeKit.shade(skull, .skin)
        side.overlay("""
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ........we..
        ...Kj...ee.K
        ...Kj...ee..
        .........b..
        .........mm.
        ............
        """)
        book.add(side.sprite(name: "head.side", anchors: anchors))

        // —— 3/4 正面（朝右）—— 近侧的眼睛宽（2），远侧的眼睛窄（1），脸中线右移
        var q34f = ShadeKit.shade(skull, .skin)
        q34f.overlay("""
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ....we..w...
        K...ee..e.K.
        ....ee..e...
        ...bb....b..
        ......mm....
        ............
        """)
        book.add(q34f.sprite(name: "head.q34front", anchors: anchors))

        // —— 3/4 背面（朝右）—— 右侧露出耳朵和一点脸颊
        var q34b = ShadeKit.shade(skull, .skin)
        q34b.overlay("""
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ............
        ..........jK
        ..........Kj
        ..........k.
        ............
        ............
        """)
        book.add(q34b.sprite(name: "head.q34back", anchors: anchors))
    }
}
