import Foundation
import PixelKit

/// 小助手（子代理）：22 px 高的迷你小人，坐在带轮子的凳子上，抱着笔记本。角色精灵，颜色随每个小助手自己的外观。
/// 挂在衣帽架上的外套（下班工位）也在这里。
public enum HelperArt {
    public static let book: SpriteBook = {
        let b = SpriteBook()
        build(b)
        return b
    }()
    public static func sprite(_ n: String) -> IndexedSprite { book[n] }

    static func build(_ b: SpriteBook) {
        // ---------- 小助手 12×24（正面，两帧：轮子花纹不同）----------
        func helper(_ wheel: Int) -> Grid {
            var g = Grid(w: 12, h: 24)
            // 头：圆脸 8×8 + 发盖
            let head = ShadeKit.shade(Bitmap("""
            ..######..
            .########.
            ##########
            ##########
            ##########
            ##########
            .########.
            ..######..
            """), .skin)
            g.overlay(head, dx: 1, dy: 0)
            let hair = ShadeKit.shade(Bitmap("""
            ..######..
            .########.
            ##########
            ###....###
            ##......##
            """), .hair)
            g.overlay(hair, dx: 1, dy: -0)
            g.overlay("""
            ............
            ............
            ............
            ............
            ............
            ....e..e....
            ............
            .....mm.....
            """)
            // 身体：肩 + 抱着的笔记本
            let body = ShadeKit.shade(Bitmap("""
            .########.
            ##########
            ##########
            ##########
            ##########
            .########.
            """), .cloth)
            g.overlay(body, dx: 1, dy: 8)
            g.overlay("""
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ...aaaaaa...
            ...aAAAAa...
            ...aAAAAa...
            ...aaaaaa...
            ............
            """)
            // 手扶在笔记本两侧
            g[2, 11] = Role.skin; g[2, 12] = Role.skin; g[9, 11] = Role.skin; g[9, 12] = Role.skin
            // 腿 + 鞋
            let pants = ShadeKit.shade(Bitmap("""
            ######
            ######
            ######
            """), .pants)
            g.overlay(pants, dx: 3, dy: 14)
            g.overlay("""
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ............
            ...oo..oo...
            """)
            // 凳子：座面 + 立柱 + 五星脚 + 轮子
            g.overlay(ShadeKit.shade(Bitmap("""
            ########
            ########
            """), .chair), dx: 2, dy: 17)
            for y in 19..<21 { g[5, y] = Role.chairSh; g[6, y] = Role.chairSh }
            for x in 1...10 { g[x, 21] = Role.chairSh }
            let w1 = wheel == 0 ? [(0, 22), (1, 22), (10, 22), (11, 22), (0, 23), (11, 23)] : [(0, 23), (1, 23), (10, 23), (11, 23), (0, 22), (11, 22)]
            for (x, y) in w1 { g[x, y] = Role.chairSh }
            return g
        }
        b.add(helper(0).sprite(name: "helper.front.0", anchors: ["feet": IntPoint(6, 23)]))
        b.add(helper(1).sprite(name: "helper.front.1", anchors: ["feet": IntPoint(6, 23)]))

        // ---------- 挂着的外套 10×13 ----------
        var coat = Grid(w: 10, h: 13)
        coat.overlay(ShadeKit.shade(Bitmap("""
        ...####...
        ..######..
        .########.
        ##########
        ##########
        ##########
        ##########
        ##########
        ##########
        ##########
        ##########
        .########.
        """), .cloth), dx: 0, dy: 1)
        coat.overlay("""
        ....33....
        ...3..3...
        ..........
        ..........
        ....tt....
        ....tt....
        ....tt....
        ....tt....
        ....tt....
        ....tt....
        """, dx: 0, dy: 0)
        b.add(coat.sprite(name: "coat", anchors: ["hook": IntPoint(5, 0)]))
    }
}
