import Foundation
import PixelKit

/// 躯干精灵（除 tee / hoodie 的背面、正面之外）：cardigan、shirt、vest、jacket 各 5 个朝向，加上 hoodie 的 q34back / side / q34front，共 23 个。
/// 命名 `torso.<衣服>.<朝向>`；朝向都是「朝向画面右侧」的版本，朝左的直接水平翻转。
///
/// 画法和 Torso.swift 一样：先用蒙版交给 `ShadeKit.shade` 自动描边 + 上高光/阴影，再用 ASCII 覆盖细节（`.` 不动）。
/// 用到的角色：s S t 3 = 衣服 高光/基色/阴影/描边；a A u = 点缀色 基色/阴影/高光（衬衫、里层）；
/// j K 2 = 肤色 阴影/基/描边（领口里露出的脖子）；n = 白点（纽扣、拉链头）。
///
/// 通用约定（每件衣服都一样）：
///  · 第 0 行 = 肩线上沿的一行；`neck` = 脖子中心；`shoulderL/R` = 手臂接口，永远在 neck.y + 3 行。
///    有立领的夹克把颈线放在第 1 行（H = 11、neck.y = 1），所以肩、下摆在头下面的绝对位置和别的衣服完全一样。
///  · 手臂（Limbs.drawArm / 手臂精灵）从 shoulderL/R 锚点出发、盖在肩袖那两列上：袖子颜色要和这件衣服的「袖山」一致
///    （见每个 build 函数标题里的说明：vest 是点缀色，其余是衣服色）。
///  · 躯干下半部分会被椅子靠背（背面）或大腿（正面坐姿）盖住 3 行左右，所以身份特征都放在上半身（领口、肩线、后背上部），
///    而且在「长发盖住后领」时还剩两行可见的后背上也放了标志（罗纹 / 工字褶 / 横缝 / 点缀色袖）。
extension CharacterArt {
    static func buildOutfits(_ book: SpriteBook) {
        buildCardiganTorso(book)
        buildShirtTorso(book)
        buildVestTorso(book)
        buildJacketTorso(book)
        buildHoodieExtraViews(book)
    }

    // MARK: - 小工具
    /// 点缀色（衬衫、里层）的材质：点缀色没有单独的描边色，所以描边用点缀影 A。
    fileprivate static let outfitAccentMat = Material(hi: Role.accent2, base: Role.accent, sh: Role.accentSh, out: Role.accentSh)

    fileprivate static func addOutfitTorso(_ book: SpriteBook, _ outfit: String, _ facing: String, _ g: Grid,
                                     neck: IntPoint, sl: IntPoint, sr: IntPoint) {
        precondition(g.w == 14, "torso.\(outfit).\(facing) 宽度是 \(g.w)，应为 14")
        book.add(g.sprite(name: "torso.\(outfit).\(facing)", anchors: ["neck": neck, "shoulderL": sl, "shoulderR": sr]))
    }

    /// 一个小部件（这里是夹克的立领）：单独描边 + 上光，叠在身体上，所以它自己带着「左上亮、右下暗」的边。
    fileprivate static func outfitLayer(_ rows: String, _ mat: Material = .cloth) -> Grid {
        let b = Bitmap(rows)
        precondition(b.w <= 14, "layer 宽度超过 14")
        return ShadeKit.shade(b, mat)
    }

    // MARK: - 开衫 cardigan
    // 针织外套：背面 = 亮色的围巾领 + 竖向罗纹（s|t 成对）+ 罗纹下摆；正面 / 3/4 = 敞开，里面是点缀色的衬衫（a/A/u），
    //   衬衫的领角 + 一排小纽扣（u），开衫的门襟上 3 颗 n 白纽扣；侧面窄身，最前面一列是露出来的衬衫。
    // 肩袖：两侧第 0 / 13 列、第 2–4 行，衣服色（针织，手臂用衣服色长袖）。
    fileprivate static func buildCardiganTorso(_ book: SpriteBook) {
        let sl = IntPoint(1, 3), sr = IntPoint(12, 3)
        // ---- 背面 ----
        var back = ShadeKit.shade(Bitmap("""
        ...########...
        .############.
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        .############.
        """), .cloth)
        back.overlay("""
        ..............
        ..t.ssssss.t..
        ...t.SSSS.t...
        ....tttttt....
        ...st.st.st...
        ...st.st.st...
        ...st.st.st...
        ..tttttttttt..
        ..StStStStSt..
        """)
        addOutfitTorso(book, "cardigan", "back", back, neck: IntPoint(7, 0), sl: sl, sr: sr)

        // ---- 3/4 背面 ----
        var q34b = ShadeKit.shade(Bitmap("""
        ....########..
        .############.
        ##############
        ##############
        .#############
        ..############
        ..############
        ..############
        ..############
        ..############
        """), .cloth)
        q34b.overlay("""
        ..............
        ...t.ssssss.t.
        ....t.SSSS.t..
        .....tttttt...
        ....st.st.st..
        ....st.st.st..
        ....st.st.st..
        ...tttttttttt.
        ...StStStStSt.
        """)
        addOutfitTorso(book, "cardigan", "q34back", q34b, neck: IntPoint(8, 0), sl: sl, sr: sr)

        // ---- 侧面 ----
        var side = ShadeKit.shade(Bitmap("""
        ....######....
        ...#######....
        ...#######....
        ...#######....
        ...#######....
        ...#######....
        ...#######....
        ...#######....
        ...#######....
        ...#######....
        """), .cloth)
        side.overlay("""
        ..............
        ....sssss.....
        ....tttt......
        ........n.....
        ....st........
        ........n.....
        ....st........
        ........n.....
        ....StStS.....
        """)
        // 衬衫：最前面一列
        side.overlay("""
        ..............
        ..............
        ..........u...
        ..........a...
        ..........a...
        ..........a...
        ..........a...
        ..........a...
        ..........a...
        ..........A...
        """)
        addOutfitTorso(book, "cardigan", "side", side, neck: IntPoint(7, 0), sl: IntPoint(6, 3), sr: IntPoint(7, 3))

        // ---- 3/4 正面 ----
        var q34f = ShadeKit.shade(Bitmap("""
        ..####....##..
        .#####....###.
        ######....####
        #######..#####
        #######..####.
        #######..###..
        #######..###..
        #######..###..
        #######..###..
        #######..###..
        """), .cloth)
        q34f.overlay("""
        ..............
        ..............
        ..t...........
        ...t.n........
        ...t..........
        ...t.n........
        ...t..........
        ...t.n........
        .tStSt....t...
        """)
        q34f.overlay("""
        ......jKKj....
        ......aKKa....
        ......uKKa....
        .......ua.....
        .......aA.....
        .......aA.....
        .......aA.....
        .......aA.....
        .......aA.....
        .......AA.....
        """)
        q34f.overlay("""
        ..............
        ..............
        ..............
        ..............
        .......u......
        ..............
        .......u......
        ..............
        .......u......
        """)
        addOutfitTorso(book, "cardigan", "q34front", q34f, neck: IntPoint(8, 0), sl: sl, sr: sr)

        // ---- 正面 ----
        var front = ShadeKit.shade(Bitmap("""
        ..###....###..
        .####....####.
        #####....#####
        ######..######
        ######..######
        .#####..#####.
        .#####..#####.
        .#####..#####.
        .#####..#####.
        .#####..#####.
        """), .cloth)
        front.overlay("""
        ..............
        ..............
        ..t........t..
        ...tn.....t...
        ...t.....st...
        ...tn....st...
        ...t.....st...
        ...tn....st...
        ..tSt....tSt..
        """)
        front.overlay("""
        .....jKKj.....
        .....aKKa.....
        .....uKKa.....
        ......ua......
        ......aA......
        ......aA......
        ......aA......
        ......aA......
        ......aA......
        ......AA......
        """)
        front.overlay("""
        ..............
        ..............
        ..............
        ..............
        ......u.......
        ..............
        ......u.......
        ..............
        ......u.......
        """)
        addOutfitTorso(book, "cardigan", "front", front, neck: IntPoint(7, 0), sl: sl, sr: sr)
    }

    // MARK: - 衬衫 shirt
    // 全身衣服色：背面 = 领子亮边 + 领口下的弧形压影线（两端是领角）+ 背中的工字褶；正面 = 两片亮领角、一排纽扣、胸袋、弧形下摆。
    // 肩袖：两侧第 0 / 13 列、第 2–4 行，衣服色（袖口略挽画在手臂上）。
    fileprivate static func buildShirtTorso(_ book: SpriteBook) {
        let sl = IntPoint(1, 3), sr = IntPoint(12, 3)
        // ---- 背面：领子一圈亮边 + 领口下的压影线、背中的工字褶；下摆是弧形的衬衫尾 ----
        var back = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        ..##########..
        """), .cloth)
        back.overlay("""
        ..............
        ..............
        ....tttttt....
        ...t.ts.t.t...
        .....ts.t.....
        .....ts.t.....
        .....ts.t.....
        .....ts.t.....
        """)
        addOutfitTorso(book, "shirt", "back", back, neck: IntPoint(7, 0), sl: sl, sr: sr)

        // ---- 3/4 背面 ----
        var q34b = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        .#############
        ..############
        ..############
        ..############
        ..############
        ...##########.
        """), .cloth)
        q34b.overlay("""
        ..............
        ..............
        .....tttttt...
        ....t.ts.t.t..
        ......ts.t....
        ......ts.t....
        ......ts.t....
        ......ts.t....
        """)
        addOutfitTorso(book, "shirt", "q34back", q34b, neck: IntPoint(8, 0), sl: sl, sr: sr)

        // ---- 侧面：领子的一片尖角搭在胸前 ----
        var side = ShadeKit.shade(Bitmap("""
        ....######....
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...#######....
        """), .cloth)
        side.overlay("""
        ..............
        ..............
        ........ss....
        ........ts....
        ........s.....
        ........s.....
        ........s.....
        ........s.....
        ........s.....
        """)
        addOutfitTorso(book, "shirt", "side", side, neck: IntPoint(7, 0), sl: IntPoint(6, 3), sr: IntPoint(7, 3))

        // ---- 3/4 正面 ----
        var q34f = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        #############.
        ############..
        ############..
        ############..
        ############..
        .###########..
        """), .cloth)
        q34f.overlay("""
        ......jKKj....
        .......KK.....
        .....ss22s....
        .....tssst....
        ......ttn.....
        .......t......
        .......tn.....
        .......t......
        .......tn.....
        """)
        addOutfitTorso(book, "shirt", "q34front", q34f, neck: IntPoint(8, 0), sl: sl, sr: sr)

        // ---- 正面：领子两个亮尖角、一排纽扣、胸袋 ----
        var front = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        ..##########..
        """), .cloth)
        front.overlay("""
        .....jKKj.....
        ......KK......
        ....ss22ss....
        ....tsssst....
        .....ttnt.....
        ......t.sss...
        ...t..tnsSt...
        ...t..t.ttt...
        ......tn......
        """)
        addOutfitTorso(book, "shirt", "front", front, neck: IntPoint(7, 0), sl: sl, sr: sr)
    }

    // MARK: - 针织背心 vest
    // 外面是背心（衣服色，人字斜纹 + 罗纹下摆，正面 V 领），里面是点缀色的衬衫：领子、两边露出的袖子、下摆的衬衫尾都是点缀色。
    // 肩袖：左侧第 0–1 列、右侧第 12–13 列，第 1–4 行 = 点缀色（左列 A/u，右列 a/A）；手臂的袖子要用点缀色（BuddyRig.sleeve 已经是 .accent）。
    fileprivate static func buildVestTorso(_ book: SpriteBook) {
        let sl = IntPoint(1, 3), sr = IntPoint(12, 3)
        /// 人字（V 形）斜纹：只在「衣服基色」的格子上打 t；左半 ↘、右半 ↙，以 mid 为对称轴。
        func chevron(_ g: inout Grid, rows: ClosedRange<Int>, mid: Int) {
            for y in rows { for x in max(0, mid - 4)..<min(g.w, mid + 4) where g[x, y] == Role.cloth {
                let xm = x < mid ? x : 2 * mid - 1 - x
                if (xm - y + 64) % 4 == 0 { g[x, y] = Role.clothSh }
            } }
        }
        // ---- 背面：衬衫领子从背心的后领口冒出来，衬衫袖露在袖笼外 ----
        var back = ShadeKit.shade(Bitmap("""
        ....######....
        .############.
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        ..##########..
        """), outfitAccentMat)
        var vestB = ShadeKit.shade(Bitmap("""
        ..............
        ...##....##...
        ..###....###..
        ..##########..
        ..##########..
        .############.
        .############.
        .############.
        .############.
        """), .cloth)
        chevron(&vestB, rows: 4...7, mid: 7)
        vestB.overlay("""
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..StStStStSt..
        """)
        back.overlay(vestB)
        back.overlay("""
        ..............
        ..............
        ............a.
        ............a.
        ............a.
        """)   // 右边的衬衫袖：底色 + 描边（只有两列，不能全是暗色）
        addOutfitTorso(book, "vest", "back", back, neck: IntPoint(7, 0), sl: sl, sr: sr)

        // ---- 3/4 背面 ----
        var q34b = ShadeKit.shade(Bitmap("""
        .....######...
        .############.
        ##############
        ##############
        .#############
        ..############
        ..############
        ..############
        ..############
        ...##########.
        """), outfitAccentMat)
        var vestQB = ShadeKit.shade(Bitmap("""
        ..............
        ....##....##..
        ...###....###.
        ...##########.
        ...##########.
        ..############
        ..############
        ..############
        ..############
        """), .cloth)
        chevron(&vestQB, rows: 4...7, mid: 8)
        vestQB.overlay("""
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ...StStStStSt.
        """)
        q34b.overlay(vestQB)
        addOutfitTorso(book, "vest", "q34back", q34b, neck: IntPoint(8, 0), sl: sl, sr: sr)

        // ---- 侧面：袖笼是个洞，里面露出衬衫袖（点缀色，圆筒状）----
        var side = ShadeKit.shade(Bitmap("""
        ....######....
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...#######....
        """), outfitAccentMat)
        var vestS = ShadeKit.shade(Bitmap("""
        ..............
        ...########...
        ...##...###...
        ...##...###...
        ...##...###...
        ...###.####...
        ...########...
        ...########...
        ...########...
        """), .cloth)
        vestS.overlay("""
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ....StStSt....
        """)
        side.overlay(vestS)
        side.overlay("""
        ..............
        ..............
        .....uaa......
        .....aaa......
        .....aaa......
        ......aA......
        """)
        addOutfitTorso(book, "vest", "side", side, neck: IntPoint(7, 0), sl: IntPoint(6, 3), sr: IntPoint(7, 3))

        // ---- 3/4 正面 ----
        var q34f = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        #############.
        ############..
        ############..
        ############..
        ############..
        .###########..
        """), outfitAccentMat)
        var vestQF = ShadeKit.shade(Bitmap("""
        ..............
        ..###......##.
        ..####....###.
        ..#####..####.
        ..#####..####.
        .###########..
        .###########..
        .###########..
        .###########..
        """), .cloth)
        chevron(&vestQF, rows: 5...7, mid: 8)
        vestQF.overlay("""
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..StStStStS...
        """)
        q34f.overlay(vestQF)
        q34f.overlay("""
        ......jKKj....
        .....uuKKaa...
        ......u22a....
        .......ua.....
        .......An.....
        """)
        addOutfitTorso(book, "vest", "q34front", q34f, neck: IntPoint(8, 0), sl: sl, sr: sr)

        // ---- 正面：V 领，衬衫领子在 V 里 ----
        var front = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        ..##########..
        """), outfitAccentMat)
        var vestF = ShadeKit.shade(Bitmap("""
        ..............
        ..##......##..
        ..###....###..
        ..####..####..
        ..####..####..
        .############.
        .############.
        .############.
        .############.
        """), .cloth)
        chevron(&vestF, rows: 5...7, mid: 7)
        vestF.overlay("""
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..............
        ..StStStStSt..
        """)
        front.overlay(vestF)
        front.overlay("""
        ..............
        ..............
        ............a.
        ............a.
        ............a.
        """)
        front.overlay("""
        .....jKKj.....
        ....uuKKaa....
        .....u22a.....
        ......ua......
        ......An......
        """)
        addOutfitTorso(book, "vest", "front", front, neck: IntPoint(7, 0), sl: sl, sr: sr)
    }

    // MARK: - 夹克 jacket
    // 罗纹立领、方肩（第 2 行起就是 14 宽）、插肩缝、拉链、斜插袋、罗纹下摆；背面有一条横向拼接缝（第 5–6 行）和背中缝。
    // 颈线在第 1 行（neck.y = 1，高 11），肩锚点在第 4 行。
    // 肩袖：两侧第 0 / 13 列、第 2–6 行，衣服色（手臂用衣服色长袖，袖口可以画罗纹）。
    fileprivate static func buildJacketTorso(_ book: SpriteBook) {
        let sl = IntPoint(1, 4), sr = IntPoint(12, 4)
        // ---- 背面：罗纹立领、插肩缝（领角斜下到腋下）、横向拼接缝、背中缝、罗纹下摆 ----
        var back = ShadeKit.shade(Bitmap("""
        ..............
        ...########...
        ##############
        ##############
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        """), .cloth)
        back.overlay("""
        ..............
        ..............
        ..............
        ..............
        ...t......t...
        ..t.tttttt.t..
        .t.ssstssss.t.
        ......t.......
        ..tttttttttt..
        ..StStStStSt..
        """)
        back.overlay(outfitLayer("""
        ...########...
        ...########...
        ...########...
        ...########...
        """))
        back.overlay("""
        ..............
        .....t.t......
        .....t.t......
        ...tttttttt...
        """)
        addOutfitTorso(book, "jacket", "back", back, neck: IntPoint(7, 1), sl: sl, sr: sr)

        // ---- 3/4 背面 ----
        var q34b = ShadeKit.shade(Bitmap("""
        ..............
        ....########..
        ##############
        ##############
        ##############
        .#############
        ..############
        ..############
        ..############
        ..############
        ..############
        """), .cloth)
        q34b.overlay("""
        ..............
        ..............
        ..............
        ..............
        ....t......t..
        ...t.tttttt.t.
        ..t....t......
        .......t......
        ...tttttttttt.
        ...StStStStSt.
        """)
        q34b.overlay(outfitLayer("""
        ....########..
        ....########..
        ....########..
        ....########..
        """))
        q34b.overlay("""
        ..............
        ......t.t.....
        ......t.t.....
        ....tttttttt..
        """)
        addOutfitTorso(book, "jacket", "q34back", q34b, neck: IntPoint(8, 1), sl: sl, sr: sr)

        // ---- 侧面 ----
        var side = ShadeKit.shade(Bitmap("""
        ..............
        ....######....
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        """), .cloth)
        side.overlay(outfitLayer("""
        ....######....
        ....######....
        ....######....
        ....######....
        """))
        side.overlay("""
        ..............
        .....t.t......
        .....t.t.t....
        ....tttttt....
        .........s....
        .........t....
        .........s....
        .........t....
        ....tttttt....
        ....StStSt....
        """)
        addOutfitTorso(book, "jacket", "side", side, neck: IntPoint(7, 1), sl: IntPoint(6, 4), sr: IntPoint(7, 4))

        // ---- 3/4 正面 ----
        var q34f = ShadeKit.shade(Bitmap("""
        ..............
        ....########..
        ##############
        ##############
        ##############
        ##############
        #############.
        ############..
        ############..
        ############..
        ############..
        """), .cloth)
        q34f.overlay(outfitLayer("""
        ....########..
        ....########..
        ....########..
        ....########..
        """))
        q34f.overlay("""
        ..............
        .......jj.....
        .......KK.....
        ....tttttttt..
        ...t...st.....
        ..t....st.....
        .t..t..st.....
        ..tt...st.....
        ..ttttttttt...
        ..StStStStS...
        """)
        q34f.overlay("""
        ..............
        ..............
        ..............
        ........n.....
        """)
        addOutfitTorso(book, "jacket", "q34front", q34f, neck: IntPoint(8, 1), sl: sl, sr: sr)

        // ---- 正面：罗纹立领、拉链、斜插袋、罗纹下摆 ----
        var front = ShadeKit.shade(Bitmap("""
        ..............
        ...########...
        ##############
        ##############
        ##############
        ##############
        ##############
        .############.
        .############.
        .############.
        .############.
        """), .cloth)
        front.overlay(outfitLayer("""
        ...########...
        ...########...
        ...########...
        ...########...
        """))
        front.overlay("""
        ..............
        ......jj......
        ......KK......
        ...tttttttt...
        ...t..st..t...
        ..t...st...t..
        .t..t.st.t..t.
        ..tt..st..tt..
        ..tttttttttt..
        ..StStStStSt..
        """)
        front.overlay("""
        ..............
        ..............
        ..............
        .......n......
        """)
        addOutfitTorso(book, "jacket", "front", front, neck: IntPoint(7, 1), sl: sl, sr: sr)
    }

    // MARK: - 卫衣 hoodie 的另外三个朝向（背面、正面在 Torso.swift）
    // 兜帽在背面 / 3/4 背面 / 侧面是脖子后面的一团布（neck.y = 2，高 12）；3/4 正面和正面一样是翻下来的 U 形领口（neck.y = 0）。
    // 肩袖：和已有的 torso.hoodie.back 一样（背面 / 侧面第 4–7 行，锚点第 5 行；3/4 正面第 2–4 行，锚点第 3 行）。
    fileprivate static func buildHoodieExtraViews(_ book: SpriteBook) {
        let sl = IntPoint(1, 5), sr = IntPoint(12, 5)
        // ---- 3/4 背面：兜帽是脖子后面的一团布（和 torso.hoodie.back 同样的画法，整体右移 1 列）----
        var q34b = ShadeKit.shade(Bitmap("""
        ....########..
        ...##########.
        .############.
        .############.
        ##############
        ##############
        ##############
        .#############
        ..############
        ..############
        ..############
        ..############
        """), .cloth)
        q34b.overlay("""
        ..............
        .....tttttt...
        ....t......t..
        ....t..hh..t..
        ..............
        ......tt.tt...
        .......t..t...
        """)
        addOutfitTorso(book, "hoodie", "q34back", q34b, neck: IntPoint(8, 2), sl: sl, sr: sr)

        // ---- 侧面：兜帽鼓在脖子后面（画面左侧）----
        var side = ShadeKit.shade(Bitmap("""
        ..###.........
        .#####........
        .#########....
        .##########...
        ..#########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        ...########...
        """), .cloth)
        side.overlay("""
        ..............
        ..............
        .....t........
        .....t........
        ....t.........
        """)
        addOutfitTorso(book, "hoodie", "side", side, neck: IntPoint(7, 2), sl: IntPoint(6, 5), sr: IntPoint(7, 5))

        // ---- 3/4 正面：兜帽翻下来的 U 形领口（和 torso.hoodie.front 同样的画法，右移 1 列）----
        var q34f = ShadeKit.shade(Bitmap("""
        ..##########..
        .############.
        ##############
        ##############
        #############.
        ############..
        ############..
        ############..
        ############..
        ############..
        """), .cloth)
        q34f.overlay("""
        ..............
        .....t2KK2t...
        .....t.22.t...
        .....t....t...
        ......t..t....
        .......tt.....
        """)
        addOutfitTorso(book, "hoodie", "q34front", q34f, neck: IntPoint(8, 0), sl: IntPoint(1, 3), sr: IntPoint(12, 3))
    }
}
